name: 🐞 Bug
description: Create a report to help us improve Dinosaur Exploder game and/or our documentation
title: "[Bug]: <title>"
labels: [Bug]
body:
- type: checkboxes
  attributes:
    label: 👉 Please confirm the following
    options:
      - label: I agree to follow the [Code of Conduct](https://github.com/dylan-power/dinosaur-exploder/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
        required: true
      - label: I checked the [current issues](https://github.com/dylan-power/dinosaur-exploder/issues) for duplicate bugs.
        required: true
- type: textarea
  attributes:
    label: ❌ Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: ✅ Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
      required: false
- type: textarea
  attributes:
    label: 🚩 Steps To Reproduce
    description: Steps to reproduce the behavior. Link some screenshots if you want.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error when I click on ...
  validations:
    required: false
- type: textarea
  attributes:
    label: 💻 Environment
    description: |
      Examples: |
        - **OS**: Ubuntu 20.04 / Windows 11
        - **JDK Java**: 17.0.1
        - **JavaFX**: 17
        - **Game Version**: 1.0.0
    value: |
      - OS:
      - Game version: 1.0.0
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: ℹ️ Additional information
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: markdown
  attributes:
    value: Thanks for taking the time to fill out this bug report! ❤️ Thanks to contribute to this project 🦖